<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('SERVICIOS_BASICOS', 'doctrine');

/**
 * BaseSERVICIOS_BASICOS
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $sb_id
 * @property string $sb_entidad
 * @property string $sb_entidad_alias
 * @property string $sb_direccion
 * @property string $sb_sitio_web
 * @property Doctrine_Collection $CONTRATAR_SB
 * @property Doctrine_Collection $TELEFONOS
 * 
 * @method integer             getSbId()             Returns the current record's "sb_id" value
 * @method string              getSbEntidad()        Returns the current record's "sb_entidad" value
 * @method string              getSbEntidadAlias()   Returns the current record's "sb_entidad_alias" value
 * @method string              getSbDireccion()      Returns the current record's "sb_direccion" value
 * @method string              getSbSitioWeb()       Returns the current record's "sb_sitio_web" value
 * @method Doctrine_Collection getCONTRATARSB()      Returns the current record's "CONTRATAR_SB" collection
 * @method Doctrine_Collection getTELEFONOS()        Returns the current record's "TELEFONOS" collection
 * @method SERVICIOS_BASICOS   setSbId()             Sets the current record's "sb_id" value
 * @method SERVICIOS_BASICOS   setSbEntidad()        Sets the current record's "sb_entidad" value
 * @method SERVICIOS_BASICOS   setSbEntidadAlias()   Sets the current record's "sb_entidad_alias" value
 * @method SERVICIOS_BASICOS   setSbDireccion()      Sets the current record's "sb_direccion" value
 * @method SERVICIOS_BASICOS   setSbSitioWeb()       Sets the current record's "sb_sitio_web" value
 * @method SERVICIOS_BASICOS   setCONTRATARSB()      Sets the current record's "CONTRATAR_SB" collection
 * @method SERVICIOS_BASICOS   setTELEFONOS()        Sets the current record's "TELEFONOS" collection
 * 
 * @package    dml
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSERVICIOS_BASICOS extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('SERVICIOS_BASICOS');
        $this->hasColumn('sb_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('sb_entidad', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('sb_entidad_alias', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('sb_direccion', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('sb_sitio_web', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 100,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('CONTRATAR_SB', array(
             'local' => 'sb_id',
             'foreign' => 'servicios_basicos_sb_id'));

        $this->hasMany('TELEFONOS', array(
             'local' => 'sb_id',
             'foreign' => 'servicios_basicos_sb_id'));
    }
}