<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('RESPALDO_CONTRATOS', 'doctrine');

/**
 * BaseRESPALDO_CONTRATOS
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $rc_id
 * @property blob $rc_pdf
 * @property integer $contrato_ip_cip_id
 * @property CONTRATO_IP $CONTRATO_IP
 * 
 * @method integer            getRcId()               Returns the current record's "rc_id" value
 * @method blob               getRcPdf()              Returns the current record's "rc_pdf" value
 * @method integer            getContratoIpCipId()    Returns the current record's "contrato_ip_cip_id" value
 * @method CONTRATO_IP        getCONTRATOIP()         Returns the current record's "CONTRATO_IP" value
 * @method RESPALDO_CONTRATOS setRcId()               Sets the current record's "rc_id" value
 * @method RESPALDO_CONTRATOS setRcPdf()              Sets the current record's "rc_pdf" value
 * @method RESPALDO_CONTRATOS setContratoIpCipId()    Sets the current record's "contrato_ip_cip_id" value
 * @method RESPALDO_CONTRATOS setCONTRATOIP()         Sets the current record's "CONTRATO_IP" value
 * 
 * @package    dml
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRESPALDO_CONTRATOS extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('RESPALDO_CONTRATOS');
        $this->hasColumn('rc_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('rc_pdf', 'blob', null, array(
             'type' => 'blob',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('contrato_ip_cip_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('CONTRATO_IP', array(
             'local' => 'contrato_ip_cip_id',
             'foreign' => 'cip_id'));
    }
}