<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TELEFONOS', 'doctrine');

/**
 * BaseTELEFONOS
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $te_id
 * @property string $te_numero
 * @property string $te_ext
 * @property integer $servicios_basicos_sb_id
 * @property SERVICIOS_BASICOS $SERVICIOS_BASICOS
 * 
 * @method integer           getTeId()                    Returns the current record's "te_id" value
 * @method string            getTeNumero()                Returns the current record's "te_numero" value
 * @method string            getTeExt()                   Returns the current record's "te_ext" value
 * @method integer           getServiciosBasicosSbId()    Returns the current record's "servicios_basicos_sb_id" value
 * @method SERVICIOS_BASICOS getSERVICIOSBASICOS()        Returns the current record's "SERVICIOS_BASICOS" value
 * @method TELEFONOS         setTeId()                    Sets the current record's "te_id" value
 * @method TELEFONOS         setTeNumero()                Sets the current record's "te_numero" value
 * @method TELEFONOS         setTeExt()                   Sets the current record's "te_ext" value
 * @method TELEFONOS         setServiciosBasicosSbId()    Sets the current record's "servicios_basicos_sb_id" value
 * @method TELEFONOS         setSERVICIOSBASICOS()        Sets the current record's "SERVICIOS_BASICOS" value
 * 
 * @package    dml
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTELEFONOS extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('TELEFONOS');
        $this->hasColumn('te_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('te_numero', 'string', 9, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 9,
             ));
        $this->hasColumn('te_ext', 'string', 5, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 5,
             ));
        $this->hasColumn('servicios_basicos_sb_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('SERVICIOS_BASICOS', array(
             'local' => 'servicios_basicos_sb_id',
             'foreign' => 'sb_id'));
    }
}