<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('REMUNERACION', 'doctrine');

/**
 * BaseREMUNERACION
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $re_id
 * @property string $re_nombre
 * @property string $re_alias
 * @property decimal $re_valor
 * @property Doctrine_Collection $CONTRATO_IP
 * 
 * @method integer             getReId()        Returns the current record's "re_id" value
 * @method string              getReNombre()    Returns the current record's "re_nombre" value
 * @method string              getReAlias()     Returns the current record's "re_alias" value
 * @method decimal             getReValor()     Returns the current record's "re_valor" value
 * @method Doctrine_Collection getCONTRATOIP()  Returns the current record's "CONTRATO_IP" collection
 * @method REMUNERACION        setReId()        Sets the current record's "re_id" value
 * @method REMUNERACION        setReNombre()    Sets the current record's "re_nombre" value
 * @method REMUNERACION        setReAlias()     Sets the current record's "re_alias" value
 * @method REMUNERACION        setReValor()     Sets the current record's "re_valor" value
 * @method REMUNERACION        setCONTRATOIP()  Sets the current record's "CONTRATO_IP" collection
 * 
 * @package    dml
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseREMUNERACION extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('REMUNERACION');
        $this->hasColumn('re_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('re_nombre', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('re_alias', 'string', 7, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 7,
             ));
        $this->hasColumn('re_valor', 'decimal', 10, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 10,
             'scale' => '2',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('CONTRATO_IP', array(
             'local' => 're_id',
             'foreign' => 'remuneracion_re_id'));
    }
}