<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('INGRESO_MONETARIO', 'doctrine');

/**
 * BaseINGRESO_MONETARIO
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $im_id
 * @property date $im_fecha
 * @property string $im_razon
 * @property decimal $im_valor
 * @property integer $persona_pe_id
 * @property PERSONA $PERSONA
 * 
 * @method integer           getImId()          Returns the current record's "im_id" value
 * @method date              getImFecha()       Returns the current record's "im_fecha" value
 * @method string            getImRazon()       Returns the current record's "im_razon" value
 * @method decimal           getImValor()       Returns the current record's "im_valor" value
 * @method integer           getPersonaPeId()   Returns the current record's "persona_pe_id" value
 * @method PERSONA           getPERSONA()       Returns the current record's "PERSONA" value
 * @method INGRESO_MONETARIO setImId()          Sets the current record's "im_id" value
 * @method INGRESO_MONETARIO setImFecha()       Sets the current record's "im_fecha" value
 * @method INGRESO_MONETARIO setImRazon()       Sets the current record's "im_razon" value
 * @method INGRESO_MONETARIO setImValor()       Sets the current record's "im_valor" value
 * @method INGRESO_MONETARIO setPersonaPeId()   Sets the current record's "persona_pe_id" value
 * @method INGRESO_MONETARIO setPERSONA()       Sets the current record's "PERSONA" value
 * 
 * @package    dml
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseINGRESO_MONETARIO extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('INGRESO_MONETARIO');
        $this->hasColumn('im_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('im_fecha', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('im_razon', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('im_valor', 'decimal', 10, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 10,
             'scale' => '2',
             ));
        $this->hasColumn('persona_pe_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('PERSONA', array(
             'local' => 'persona_pe_id',
             'foreign' => 'pe_id'));
    }
}