<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CONTRATO_IP', 'doctrine');

/**
 * BaseCONTRATO_IP
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $cip_id
 * @property date $cip_fecha_ingreso
 * @property date $cip_fecha_salida
 * @property string $cip_motivos_salida
 * @property string $cip_actividad_desarrollada
 * @property integer $cip_activo
 * @property integer $institucion_publica_ip_id
 * @property integer $remuneracion_re_id
 * @property integer $persona_pe_id
 * @property INSTITUCION_PUBLICA $INSTITUCION_PUBLICA
 * @property REMUNERACION $REMUNERACION
 * @property PERSONA $PERSONA
 * @property Doctrine_Collection $RESPALDO_CONTRATOS
 * 
 * @method integer             getCipId()                      Returns the current record's "cip_id" value
 * @method date                getCipFechaIngreso()            Returns the current record's "cip_fecha_ingreso" value
 * @method date                getCipFechaSalida()             Returns the current record's "cip_fecha_salida" value
 * @method string              getCipMotivosSalida()           Returns the current record's "cip_motivos_salida" value
 * @method string              getCipActividadDesarrollada()   Returns the current record's "cip_actividad_desarrollada" value
 * @method integer             getCipActivo()                  Returns the current record's "cip_activo" value
 * @method integer             getInstitucionPublicaIpId()     Returns the current record's "institucion_publica_ip_id" value
 * @method integer             getRemuneracionReId()           Returns the current record's "remuneracion_re_id" value
 * @method integer             getPersonaPeId()                Returns the current record's "persona_pe_id" value
 * @method INSTITUCION_PUBLICA getINSTITUCIONPUBLICA()         Returns the current record's "INSTITUCION_PUBLICA" value
 * @method REMUNERACION        getREMUNERACION()               Returns the current record's "REMUNERACION" value
 * @method PERSONA             getPERSONA()                    Returns the current record's "PERSONA" value
 * @method Doctrine_Collection getRESPALDOCONTRATOS()          Returns the current record's "RESPALDO_CONTRATOS" collection
 * @method CONTRATO_IP         setCipId()                      Sets the current record's "cip_id" value
 * @method CONTRATO_IP         setCipFechaIngreso()            Sets the current record's "cip_fecha_ingreso" value
 * @method CONTRATO_IP         setCipFechaSalida()             Sets the current record's "cip_fecha_salida" value
 * @method CONTRATO_IP         setCipMotivosSalida()           Sets the current record's "cip_motivos_salida" value
 * @method CONTRATO_IP         setCipActividadDesarrollada()   Sets the current record's "cip_actividad_desarrollada" value
 * @method CONTRATO_IP         setCipActivo()                  Sets the current record's "cip_activo" value
 * @method CONTRATO_IP         setInstitucionPublicaIpId()     Sets the current record's "institucion_publica_ip_id" value
 * @method CONTRATO_IP         setRemuneracionReId()           Sets the current record's "remuneracion_re_id" value
 * @method CONTRATO_IP         setPersonaPeId()                Sets the current record's "persona_pe_id" value
 * @method CONTRATO_IP         setINSTITUCIONPUBLICA()         Sets the current record's "INSTITUCION_PUBLICA" value
 * @method CONTRATO_IP         setREMUNERACION()               Sets the current record's "REMUNERACION" value
 * @method CONTRATO_IP         setPERSONA()                    Sets the current record's "PERSONA" value
 * @method CONTRATO_IP         setRESPALDOCONTRATOS()          Sets the current record's "RESPALDO_CONTRATOS" collection
 * 
 * @package    dml
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCONTRATO_IP extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('CONTRATO_IP');
        $this->hasColumn('cip_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('cip_fecha_ingreso', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('cip_fecha_salida', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('cip_motivos_salida', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('cip_actividad_desarrollada', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('cip_activo', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('institucion_publica_ip_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('remuneracion_re_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('persona_pe_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('INSTITUCION_PUBLICA', array(
             'local' => 'institucion_publica_ip_id',
             'foreign' => 'ip_id'));

        $this->hasOne('REMUNERACION', array(
             'local' => 'remuneracion_re_id',
             'foreign' => 're_id'));

        $this->hasOne('PERSONA', array(
             'local' => 'persona_pe_id',
             'foreign' => 'pe_id'));

        $this->hasMany('RESPALDO_CONTRATOS', array(
             'local' => 'cip_id',
             'foreign' => 'contrato_ip_cip_id'));
    }
}