<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2015/01/18 17:25:13

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=192.168.197.137;port=3306;dbname=dml',
  'username' => 'root',
  'password' => '39801981',
  'name' => 'doctrine',
)),);
