<?php

/**
 * BINARIOSTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BINARIOSTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BINARIOSTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BINARIOS');
    }
    
    public static function EntidadBINARIOS() {
        return BINARIOSTable::getInstance()
                ->createQuery('bi');
    }
}