<?php

/**
 * CONTRATO_IPTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CONTRATO_IPTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CONTRATO_IPTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CONTRATO_IP');
    }
}