<?php

/**
 * CONTRATAR_SBTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CONTRATAR_SBTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CONTRATAR_SBTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CONTRATAR_SB');
    }
}