<?php

/**
 * INGRESO_MONETARIOTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class INGRESO_MONETARIOTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object INGRESO_MONETARIOTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('INGRESO_MONETARIO');
    }
}