<?php

/**
 * INSTITUCION_PUBLICATable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class INSTITUCION_PUBLICATable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object INSTITUCION_PUBLICATable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('INSTITUCION_PUBLICA');
    }
}