<?php

/**
 * PAGOSTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PAGOSTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PAGOSTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PAGOS');
    }
}