<?php

/**
 * PAGOSTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PAGOSTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PAGOSTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PAGOS');
    }
    
    public static function EntidadPAGOS() {
        return PAGOSTable::getInstance()
                ->createQuery('pa');
    }
    
    public static function consumoMensual($data) {
        return PAGOSTable::EntidadPAGOS()
                ->innerJoin('pa.TIPO_CONSUMO tc')
                    ->addSelect('SUM(pa.pa_valor_total) as vt')
                        ->where('MONTH(pa.pa_fecha) = MONTH(CURDATE())')
                            ->andWhere('tc.tc_nombre LIKE ?',array('%'.$data.'%'));
    }
}