<?php

/**
 * PAGOSTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PAGOSTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PAGOSTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PAGOS');
    }
    
    public static function EntidadPAGOS() {
        return PAGOSTable::getInstance()
                ->createQuery('pa');
    }
    
    public static function consumoMensual($data) {
        return PAGOSTable::EntidadPAGOS()
                ->innerJoin('pa.TIPO_CONSUMO tc')
                    ->addSelect('SUM(pa.pa_valor_total) as vt')
//                        ->where('MONTH(pa.pa_fecha) = MONTH(DATE_ADD(NOW(),INTERVAL -1 MONTH))')
                        ->where('MONTH(pa.pa_fecha) = MONTH(CURDATE())')
                            ->andWhere('tc.tc_nombre LIKE ?',array('%'.$data.'%'));
    }
    
    public static function consumoDiario($fecha) {
        return PAGOSTable::EntidadPAGOS()
                ->addSelect('SUM(pa.pa_valor_total) as vtd')
                    ->where('DATE(pa.pa_fecha) = DATE(?)',array($fecha));
    }
    
    public static function cuentaConsumoDiario($fecha) {
        return PAGOSTable::EntidadPAGOS()
                ->addSelect('COUNT(pa.pa_valor_total) as ccd')
                    ->where('DATE(pa.pa_fecha) = DATE(?)',array($fecha))
                        ->fetchOne(array(), Doctrine::HYDRATE_ARRAY_SHALLOW);
    }
}