<?php

/**
 * PERSONATable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PERSONATable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PERSONATable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PERSONA');
    }
}