<?php

/**
 * RESPALDO_CONTRATOSTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RESPALDO_CONTRATOSTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RESPALDO_CONTRATOSTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RESPALDO_CONTRATOS');
    }
}