<?php

/**
 * SERVICIOS_BASICOSTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SERVICIOS_BASICOSTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SERVICIOS_BASICOSTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SERVICIOS_BASICOS');
    }
}