<?php

/**
 * TELEFONOSTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TELEFONOSTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TELEFONOSTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TELEFONOS');
    }
}