<?php

/**
 * TIPO_CONSUMOTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TIPO_CONSUMOTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TIPO_CONSUMOTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TIPO_CONSUMO');
    }
}