# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

# default values
all:
    max_per_page: 8
    max_files_per_paid: 5
    iva: 12
    ice: 15
    comision: 999.99
    numero_documento: 15
    movimientos_bancarios: 7
    sharefile_per_file: 3