# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/04-Settings

prod:
  .settings:
    no_script_name:      true
    logging_enabled:     false

dev:
  .settings:
#    error_reporting:    <?php echo (E_ALL | E_STRICT)."\n" ?>
#    Se comenta esta linea de codigo ya que la version de symfony 1.4.20 ya no 
#    esta en mantenimiento mas y genera errores con versiones actuales de PHP
#    asi que se está evitando todos los mensajes y advertencia que indica en el
#    arranque.
    error_reporting:     <?php echo ((E_STRICT) ^ E_NOTICE)."\n" ?>
    web_debug:           true
    cache:               false
    no_script_name:      false
    etag:                false

test:
  .settings:
#    error_reporting:    <?php echo (E_ALL | E_STRICT)."\n" ?>
#    Similar al caso de arriba
    error_reporting:     <?php echo ((E_STRICT) ^ E_NOTICE)."\n" ?>
    cache:               false
    web_debug:           false
    no_script_name:      false
    etag:                false

all:
  .settings:
    # Clave de seguridad para formularios (proteccion CSRF)
    csrf_secret:         fceda1eca5e88f549ac47d99ed35e441033b0c85

    # Configuracion de salida de escape
    escaping_strategy:   true
    escaping_method:     ESC_SPECIALCHARS

    # Activa el administrador de base de datos
    use_database:        true
    
    # activando modulo login ---
    login_module:        login
    login_action:        index
    secure_module:       login
    secure_action:       index
#  .actions:
#    login_module:        login
#    login_action:        index
    # --------------------------