# Puedes encontrar mas informacion sobre esto en el sitio web de symfony:
# http://www.symfony-project.org/reference/1_4/en/07-Databases

# + -------------------------------------------------------------------------- +
# Creado por Oswaldo Rojas <def.3980@gmail.com>
# Fecha: Viernes, 5 Diciembre 2014 12:20:18
#
# Acciones realizadas:
#  - Veces ejecutado configure:database     : "007"
#  - Ultima vez que se actualizo el esquema : "2015-03-30 12:12:39"
# + -------------------------------------------------------------------------- +

all:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:host=192.168.197.150;port=3306;dbname=dml'
      username: root
      password: '39801981'
