## CONTROL DE LIBRERIAS QUE SE PUEDEN USAR O NO
all:
    javascripts: [js-personal/validators, js-personal/dump]

newSuccess:
    javascripts: [jquery.form.js, autoNumeric/autoNumeric, jquery.maskedinput.js]

editSuccess:
    javascripts: [jquery.form.js, autoNumeric/autoNumeric, jquery.maskedinput.js]