<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/10/16 13:14:08

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=dml',
  'username' => 'root',
  'password' => '39801981',
  'name' => 'doctrine',
)),);
