<?php
// auto-generated by sfSecurityConfigHandler
// date: 2015/01/18 17:25:37
$this->security = array (
  'all' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 'admin',
    ),
  ),
);
