CONTRATAR_SB:
  connection: doctrine
  tableName: CONTRATAR_SB
  columns:
    csb_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    csb_identificacion:
      type: string(50)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    csb_fecha:
      type: date(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    persona_pe_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    servicios_basicos_sb_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
  relations:
    PERSONA:
      local: persona_pe_id
      foreign: pe_id
      type: one
    SERVICIOS_BASICOS:
      local: servicios_basicos_sb_id
      foreign: sb_id
      type: one
PAGOS:
  connection: doctrine
  tableName: PAGOS
  columns:
    pa_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    pa_numero_factura:
      type: string(17)
      fixed: true
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    pa_fecha:
      type: date(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    pa_detalle:
      type: string()
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    pa_iva:
      type: 'decimal(10, 2)'
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    pa_ice:
      type: 'decimal(10, 2)'
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    pa_comision:
      type: 'decimal(10, 2)'
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    pa_valor_total:
      type: 'decimal(10, 2)'
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    pa_respaldo:
      type: blob()
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    persona_pe_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
  relations:
    PERSONA:
      local: persona_pe_id
      foreign: pe_id
      type: one
PERSONA:
  connection: doctrine
  tableName: PERSONA
  columns:
    pe_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    pe_cedula:
      type: string(100)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    pe_nombres:
      type: string(100)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    pe_apellidos:
      type: string(100)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    pe_fecha_nacimiento:
      type: date(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    pe_imagen:
      type: blob()
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    pe_email:
      type: string(100)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    pe_usr:
      type: string(100)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    pe_pwd:
      type: string(50)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
  relations:
    CONTRATAR_SB:
      local: pe_id
      foreign: persona_pe_id
      type: many
    PAGOS:
      local: pe_id
      foreign: persona_pe_id
      type: many
SERVICIOS_BASICOS:
  connection: doctrine
  tableName: SERVICIOS_BASICOS
  columns:
    sb_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    sb_entidad:
      type: string(100)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    sb_entidad_alias:
      type: string(50)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    sb_direccion:
      type: string()
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    sb_sitio_web:
      type: string(100)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
  relations:
    CONTRATAR_SB:
      local: sb_id
      foreign: servicios_basicos_sb_id
      type: many
    TELEFONOS:
      local: sb_id
      foreign: servicios_basicos_sb_id
      type: many
TELEFONOS:
  connection: doctrine
  tableName: TELEFONOS
  columns:
    te_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    te_numero:
      type: string(9)
      fixed: true
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    te_ext:
      type: string(5)
      fixed: true
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    servicios_basicos_sb_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
  relations:
    SERVICIOS_BASICOS:
      local: servicios_basicos_sb_id
      foreign: sb_id
      type: one
